-- RISE FROM BROKEN V1/V2 search table
-- Run this in Supabase SQL Editor.
-- Then add your own indexed pages/documents.

create extension if not exists pg_trgm;

create table if not exists public.search_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  description text default '',
  content text default '',
  created_at timestamptz default now()
);

alter table public.search_documents enable row level security;

drop policy if exists "public can read search documents" on public.search_documents;
create policy "public can read search documents"
on public.search_documents for select
to anon, authenticated
using (true);

alter table public.search_documents
  add column if not exists search_vector tsvector
  generated always as (
    to_tsvector('english',
      coalesce(title,'') || ' ' ||
      coalesce(description,'') || ' ' ||
      coalesce(content,'')
    )
  ) stored;

create index if not exists search_documents_search_vector_idx
on public.search_documents using gin(search_vector);

insert into public.search_documents (title,url,description,content) values
('Python Programming','https://www.python.org/','Python is a programming language that lets you work quickly and integrate systems effectively.','python programming language'),
('MDN Web Docs','https://developer.mozilla.org/','Resources for developers, including HTML, CSS, JavaScript, web APIs, and modern web development.','html css javascript web development'),
('OWASP','https://owasp.org/','A community dedicated to improving software security through open projects, standards, and education.','cyber security application security'),
('GitHub','https://github.com/','Build, collaborate, and share code with developers around the world.','git code collaboration'),
('Supabase','https://supabase.com/','An open source Firebase alternative with Postgres database, authentication, storage, and more.','database postgres backend');
